version: '3.9'
services:
  app:
    env_file: .env
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    tty: true

  fuseki:
    build:
      context: .
      dockerfile: Dockerfile-fuseki
    ports:
      - "3030:3030"
    volumes:
      - "fuseki-data:/fuseki"
    environment:
      - ADMIN_PASSWORD=password

volumes:
  fuseki-data:
